---
- name: IOS Backup
  hosts: 
  - IOSprod
  gather_facts: no
  ignore_unreachable: true
  collections: 
    - cisco.ios
  vars: 
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes 
    ansible_become_method: enable  # ansible_become_method: sudo
    date_time: "{{ lookup('pipe', 'date +%Y%m%d_%H%M') }}"
  vars_files:
    login.yml
    
  tasks:      
    - name: backup config
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          filename: ios_bak_{{ inventory_hostname }}_{{ date_time }}.txt
          dir_path: /sftp/ios/
      register: output
    - debug: var=output
